# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
  - name: capability
    displayName: Requested agent capability
    type: string
  - name: environment
    type: string
    displayName: Environment name
  - name: context_path
    type: string
    default: '.'
  - name: dockerfile
    type: string
    default: 'src/Dockerfile'
  - name: image_name
    type: string
  - name: service_connection
    type: string

jobs:
  - template: run-docker-tests.yml
    parameters:
      capability: ${{ parameters.capability }}
      project_directory: '.'
      requirements_path: 'requirements.txt'
      pytest_target: 'tests'
      pytest_mark_expression: 'unit or integration'
      coverage_target: 'src'
      report_directory: 'pytest_reports/docker-tests'

  - job: BuildImage
    displayName: Build and Push Image to ACR
    dependsOn: RunDockerTests
    pool:
      name: ${{ parameters.capability }}
    steps:
      - checkout: self
        clean: true
      - template: install-az-cli.yml
      - template: build-and-push-acr.yml
        parameters:
          context_path: ${{ parameters.context_path }}
          dockerfile: ${{ parameters.dockerfile }}
          image_name: ${{ parameters.image_name }}
          tag_version: '$(Build.BuildId)'
          build_args:
            AZURE_KEY_VAULT_NAME: '$(azure_key_vault_name)'
          service_connection: ${{ parameters.service_connection }}

  - deployment: DeployWebAppContainer
    dependsOn: BuildImage
    environment: ${{ parameters.environment }}
    displayName: Deploy Image to App Service
    pool:
      name: ${{ parameters.capability }}
    strategy:
      runOnce:
        deploy:
          steps:
            - template: webapp-container-to-acr.yml
              parameters:
                webapp_name: '$(azure_webapp_service_name)'
                image_name: '${{ parameters.image_name }}/${{ parameters.image_name }}:$(Build.BuildId)'
                service_connection: ${{ parameters.service_connection }}
