# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

parameters:
  - name: capability
    displayName: Requested agent capability
    type: string
  - name: environment
    type: string
    displayName: Environment name
  - name: image_name
    displayName: ACR image image name for the deployment of Function App
    type: string
  - name: service_connection
    displayName: Resource Manager Service Connection Name
    type: string

jobs:
  - template: run-docker-tests.yml
    parameters:
      capability: ${{ parameters.capability }}
      uv_sync_args: '--group dev --extra examples'
      pytest_mark_expression: 'unit or integration'

  - job: BuildImage
    displayName: Build and Push Image to ACR
    dependsOn: RunDockerTests
    pool:
      name: ${{ parameters.capability }}
    steps:
      - checkout: self
        clean: true
      # - template: install-az-cli.yml
      - template: build-and-push-acr.yml
        parameters:
          context_path: '.'
          dockerfile: 'src/services/functions/Dockerfile'
          image_name: ${{ parameters.image_name }}
          tag_version: '$(Build.BuildId)'
          build_args:
            AZURE_KEY_VAULT_NAME: '$(azure_key_vault_name)'
            AZURE_BLOB_STORAGE_NAME: '$(azure_blob_storage_name)'
          service_connection: ${{ parameters.service_connection }}

  - deployment: DeployFunctionAppImage
    dependsOn: BuildImage
    environment: ${{ parameters.environment }}
    displayName: Deploy Image to Function App
    pool:
      name: ${{ parameters.capability }}
    strategy:
      runOnce:
        deploy:
          steps:
            - template: function-app-to-acr.yml
              parameters:
                image_name: '$(azure_container_registry_name).azurecr.io/${{ parameters.image_name }}/${{ parameters.image_name }}:$(Build.BuildId)'
                service_connection: ${{ parameters.service_connection }}